'use client'

import { useMemo,useRef,useState } from 'react'

const COUNTRIES=['Netherlands','Germany','United Kingdom','United States','Turkey','Norway','Denmark','Sweden','Finland','France','Spain','Italy','Belgium']
const STANDARDS={EU:{label:'Avrupa',note:'ATS uyumlu, sade, 1–2 sayfa.'},UK:{label:'İngiltere',note:'Kişisel detaylar minimum; deneyim ve başarı odaklı.'},US:{label:'ABD',note:'Resume formatı; fotoğraf, doğum tarihi ve uyruk çıkarılır.'}}
const TEMPLATES={classic:{label:'Classic ATS',desc:'En güvenli, tek kolon'},modern:{label:'Modern Professional',desc:'Başlık güçlü, temiz bloklar'},minimal:{label:'Minimal Executive',desc:'Kıdemli roller için sade'}}
function mergeUnique(a,b){const lines=(a+'\n'+b).split(/\n+/).map(x=>x.trim()).filter(Boolean);return [...new Set(lines)].join('\n')}
function cleanLines(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).filter(x=>!/date of birth|birth|nationality|marital|gender|passport|photo/i.test(x))}
function standardize(text,standard){const lines=cleanLines(text);const head=standard==='US'?'PROFESSIONAL SUMMARY':standard==='UK'?'PROFILE':'PROFESSIONAL PROFILE';return `${head}\n${lines.slice(0,7).join(' · ')}\n\nEXPERIENCE\n${lines.slice(7,48).join('\n')}\n\nEDUCATION & SKILLS\n${lines.slice(48).join('\n')}`}
function comparison(cv,job){const dims=[['Mezuniyet / eğitim',['bachelor','bsc','degree','university','engineering']],['Yabancı dil',['english','german','dutch','language']],['Program bilgisi',['cadmatic','autocad','plant 3d','solidworks','revit','aveva']],['Teknik uzmanlık',['piping','hvac','p&id','mechanical','design']],['Deneyim / kıdem',['senior','lead','manager','years']],['Sektör',['marine','ship','vessel','yacht','offshore']],['Liderlik',['lead','team','coordination','subcontractor']],['Class / standart',['solas','dnv','lloyd','classification','bv']],['Dokümantasyon',['documentation','isometric','spool','drawing','report']],['Lokasyon / çalışma',['remote','hybrid','onsite','relocation','permit','eu']]];const c=cv.toLowerCase(),j=`${job.title||''} ${job.description||''}`.toLowerCase();return dims.map(([label,keys])=>({label,required:keys.some(k=>j.includes(k)),matched:keys.some(k=>c.includes(k))}))}
function firstLines(text,n=8){return cleanLines(text).slice(0,n)}

export default function Home(){
 const [tab,setTab]=useState('cv'),[cv,setCv]=useState(''),[linkedin,setLinkedin]=useState(''),[linkedinUrl,setLinkedinUrl]=useState(''),[fileName,setFileName]=useState(''),[uploading,setUploading]=useState(false),[standard,setStandard]=useState('EU'),[template,setTemplate]=useState('classic'),[updatedCv,setUpdatedCv]=useState(''),[country,setCountry]=useState('Netherlands'),[jobs,setJobs]=useState([]),[sources,setSources]=useState([]),[jobRole,setJobRole]=useState(''),[jobsLoading,setJobsLoading]=useState(false),[jobsError,setJobsError]=useState(''),[packages,setPackages]=useState({}),[activeJob,setActiveJob]=useState(null);const fileRef=useRef(null)
 const cvForJobs=updatedCv||cv
 const previewLines=useMemo(()=>firstLines(updatedCv||cv,55),[updatedCv,cv])
 async function handleFile(e){const file=e.target.files?.[0];if(!file)return;setUploading(true);setFileName(file.name);try{const form=new FormData();form.append('file',file);const r=await fetch('/api/extract',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'CV okunamadı');setCv(d.text);setUpdatedCv('')}catch(err){alert(err.message||'CV yüklenemedi')}finally{setUploading(false);if(fileRef.current)fileRef.current.value=''}}
 function createCv(){const merged=mergeUnique(cv,linkedin);if(merged.length<40)return;setUpdatedCv(standardize(merged,standard))}
 async function findJobs(){if(cvForJobs.length<40)return;setJobsLoading(true);setJobsError('');setJobs([]);setPackages({});try{const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv:cvForJobs,country})});const d=await r.json();if(!r.ok)throw new Error(d.error||'İlanlar alınamadı');setJobs(d.jobs||[]);setSources(d.sources||[]);setJobRole(d.role||'')}catch(e){setJobsError(e.message||'İlanlar alınamadı')}finally{setJobsLoading(false)}}
 async function prepare(job,i){setPackages(p=>({...p,[i]:{status:'loading'}}));try{const r=await fetch('/api/tailor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv:cvForJobs,job,standard})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Hazırlanamadı');setPackages(p=>({...p,[i]:{status:'ready',...d}}));setActiveJob(i)}catch(e){setPackages(p=>({...p,[i]:{status:'error',error:e.message}}))}}
 return <main><nav className="nav wrap"><div className="brand"><span className="brandMark">J</span>JobFit</div><div className="topTabs"><button className={tab==='cv'?'active':''} onClick={()=>setTab('cv')}>CV Studio</button><button className={tab==='jobs'?'active':''} onClick={()=>setTab('jobs')}>İş Bul</button></div></nav>
 {tab==='cv'&&<><section className="hero wrap"><div className="eyebrow">JOBFIT CV STUDIO</div><h1>CV’ni hazırla. <span>Önizle. Sonra işe göre kullan.</span></h1><p>CV ve LinkedIn bilgilerini birleştir, hedef standardı ve şablonu seç, güncel CV’yi A4 görünümünde kontrol et.</p></section><section className="wrap twoCol"><div className="panel"><div className="step">01</div><h2>Kaynak CV</h2><input ref={fileRef} className="fileInput" type="file" accept=".pdf,.docx,.txt" onChange={handleFile}/><button className="uploadBox" onClick={()=>fileRef.current?.click()} disabled={uploading}><span className="uploadIcon">↑</span><strong>{uploading?'CV okunuyor…':fileName||'CV dosyası seç'}</strong><small>PDF · DOCX · TXT</small></button><textarea value={cv} onChange={e=>setCv(e.target.value)} placeholder="CV içeriği..."/></div><div className="panel"><div className="step">02</div><h2>LinkedIn bilgileri</h2><input className="textInput" value={linkedinUrl} onChange={e=>setLinkedinUrl(e.target.value)} placeholder="LinkedIn profil URL"/><p className="help">URL kaydedilir. LinkedIn tam profil verisini dışarı açmadığı için About / Experience / Skills metnini ekleyebilirsin.</p><textarea value={linkedin} onChange={e=>setLinkedin(e.target.value)} placeholder="LinkedIn profil metni..."/></div></section><section className="wrap panel"><div className="sectionHead"><div><div className="eyebrow">FORMAT</div><h2>Standart ve şablon seç</h2></div></div><div className="standardGrid">{Object.entries(STANDARDS).map(([k,v])=><button key={k} className={`standardCard ${standard===k?'selected':''}`} onClick={()=>setStandard(k)}><strong>{v.label}</strong><small>{v.note}</small></button>)}</div><div className="templateGrid">{Object.entries(TEMPLATES).map(([k,v])=><button key={k} className={`templateCard ${template===k?'selected':''}`} onClick={()=>setTemplate(k)}><span className={`templateThumb ${k}`}></span><strong>{v.label}</strong><small>{v.desc}</small></button>)}</div><div className="actionRow"><button className="analyseBtn" disabled={cv.length<40} onClick={createCv}>CV’mi oluştur <span>→</span></button></div></section><section className="wrap previewSection"><div className="sectionHead"><div><div className="eyebrow">A4 ÖNİZLEME</div><h2>Güncel CV</h2></div><span className="quality goodQ">{STANDARDS[standard].label} · {TEMPLATES[template].label}</span></div><div className={`paper ${template}`}><header><h1>{previewLines[0]||'Ad Soyad'}</h1><p>{previewLines.slice(1,3).join(' • ')||'Professional profile'}</p></header><section><h3>PROFILE</h3><p>{previewLines.slice(3,7).join(' ')||'CV oluşturduğunda burada önizleme görünecek.'}</p></section><section><h3>EXPERIENCE</h3>{previewLines.slice(7,30).map((x,i)=><p key={i}>{x}</p>)}</section><section><h3>EDUCATION & SKILLS</h3>{previewLines.slice(30,55).map((x,i)=><p key={i}>{x}</p>)}</section></div></section></>}
 {tab==='jobs'&&<><section className="hero wrap"><div className="eyebrow">JOBFIT JOB DISCOVERY</div><h1>CV’ne en uygun <span>10 ilanı sırala.</span></h1><p>CV filtreyi belirler; sen yalnızca ülkeyi seçersin. Her ilan için uygunluk kontrolü, başvuru linki, ön yazı ve ilana özel CV paketi hazırlanır.</p></section><section className="wrap panel jobFinder"><h2>Hedef ülke</h2><select value={country} onChange={e=>setCountry(e.target.value)}>{COUNTRIES.map(c=><option key={c}>{c}</option>)}</select><div className="profileHint">{cvForJobs.length>40?'✓ CV profili hazır':'Önce CV Studio’dan CV yükle'}</div><div className="actionRow"><button className="analyseBtn" disabled={cvForJobs.length<40||jobsLoading} onClick={findJobs}>{jobsLoading?'İlanlar taranıyor…':'En uygun 10 ilanı bul'} <span>→</span></button></div></section>{jobRole&&<section className="wrap roleBar"><span>CV’den çıkarılan rol</span><strong>{jobRole}</strong><b>{country}</b></section>}{jobsError&&<div className="wrap uploadError">{jobsError}</div>}{jobs.length>0&&<section className="wrap rankedJobs">{jobs.map((j,i)=>{const checks=comparison(cvForJobs,j);const req=checks.filter(x=>x.required),ok=req.filter(x=>x.matched).length,pkg=packages[i];return <article className="rankJob" key={i}><div className="rankNo">#{i+1}</div><div className="jobMain"><div className="jobTop"><div><span className="sourceBadge">{j.source}</span><h3>{j.title}</h3><p>{j.company||'Şirket bilgisi yok'} · {j.location||country}</p></div><div className="fitScore">{j.fit}%<small>uyum</small></div></div><div className="quickChecks">{checks.slice(0,5).map(x=><span key={x.label} className={x.required?(x.matched?'yes':'miss'):'neutral'}>{x.matched?'✓':'–'} {x.label}</span>)}</div><div className="jobActions">{j.url&&<a className="applyBtn" href={j.url} target="_blank" rel="noreferrer">Başvur ↗</a>}<button onClick={()=>prepare(j,i)} disabled={pkg?.status==='loading'}>{pkg?.status==='loading'?'Ön yazı hazırlanıyor…':pkg?.status==='ready'?'✓ CV güncellendi + ön yazı hazır':'Başvuru paketini hazırla'}</button></div>{pkg?.status==='ready'&&<div className="packageBox"><strong>Başvuru paketi hazır</strong><span>✓ Bu ilana özel CV güncellendi</span><span>✓ Ön yazı hazırlandı</span><button onClick={()=>setActiveJob(activeJob===i?null:i)}>{activeJob===i?'Kapat':'Paketi gör'}</button>{activeJob===i&&<div className="packagePreview"><h4>Ön yazı</h4><textarea readOnly value={pkg.coverLetter}/><h4>İlana özel CV</h4><textarea readOnly value={pkg.tailoredCv}/></div>}</div>}</div></article>})}</section>}{sources.length>0&&<section className="wrap panel sourceFallback"><h3>Kaynak aramaları</h3><p>Bir kaynak otomatik ilan listesini kapatırsa CV rolüne göre hazırlanmış aramayı doğrudan açabilirsin.</p><div className="sourceLinks">{sources.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer">{s.name} aramasını aç ↗</a>)}</div></section>}</>}
 <footer className="wrap">JobFit · CV Studio + Job Discovery</footer></main>}
