'use client'

import { useMemo, useRef, useState } from 'react'

const COUNTRIES=['Netherlands','Germany','United Kingdom','United States','Turkey','Norway','Denmark','Sweden','Finland','France','Spain','Italy','Belgium']
const STANDARDS={EU:{label:'Avrupa',note:'Sade, ATS uyumlu, 1–2 sayfa; gereksiz kişisel bilgiler azaltılır.'},UK:{label:'İngiltere',note:'Photo, yaş, medeni durum gibi bilgiler kullanılmaz; deneyim ve başarı öne çıkar.'},US:{label:'ABD',note:'Resume formatı; photo, doğum tarihi, uyruk ve kişisel detaylar çıkarılır.'}}
function mergeUnique(a,b){const lines=(a+'\n'+b).split(/\n+/).map(x=>x.trim()).filter(Boolean);return [...new Set(lines)].join('\n')}
function standardize(text,standard){let lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);lines=lines.filter(x=>!/date of birth|birth|nationality|marital|gender|passport|photo/i.test(x));const head=standard==='US'?'PROFESSIONAL SUMMARY':standard==='UK'?'PROFILE':'PROFESSIONAL PROFILE';return `${head}\n${lines.slice(0,8).join(' · ')}\n\nEXPERIENCE\n${lines.slice(8,55).join('\n')}\n\nEDUCATION & SKILLS\n${lines.slice(55).join('\n')}`}
function checklist(cv,linkedin){const dims=[['Headline / hedef rol',['mechanical','engineer','lead','manager','design']],['Deneyim tarihleri',['202','201']],['Teknik yetkinlik',['piping','hvac','p&id','cadmatic','autocad']],['Liderlik',['lead','team','coordination','manager']],['Proje / sektör',['ship','yacht','marine','vessel','ferry']],['Eğitim',['bsc','bachelor','university','degree']],['Yabancı dil',['english','german','dutch','turkish']],['Yazılım',['cadmatic','autocad','plant 3d','rhinoceros']],['Class / standart',['solas','dnv','bv','classification','lloyd']],['İletişim bilgileri',['email','phone','linkedin']]];const c=cv.toLowerCase(),l=linkedin.toLowerCase();return dims.map(([label,keys])=>({label,cv:keys.some(k=>c.includes(k)),linkedin:keys.some(k=>l.includes(k))}))}
export default function Home(){
  const [tab,setTab]=useState('cv'),[cv,setCv]=useState(''),[linkedin,setLinkedin]=useState(''),[linkedinUrl,setLinkedinUrl]=useState(''),[fileName,setFileName]=useState(''),[uploading,setUploading]=useState(false),[standard,setStandard]=useState('EU'),[updatedCv,setUpdatedCv]=useState(''),[country,setCountry]=useState('Netherlands'),[jobs,setJobs]=useState([]),[sources,setSources]=useState([]),[jobRole,setJobRole]=useState(''),[jobsLoading,setJobsLoading]=useState(false),[jobsError,setJobsError]=useState('');const fileRef=useRef(null);const checks=useMemo(()=>checklist(cv,linkedin),[cv,linkedin])
  async function handleFile(e){const file=e.target.files?.[0];if(!file)return;setUploading(true);setFileName(file.name);try{const form=new FormData();form.append('file',file);const r=await fetch('/api/extract',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'CV okunamadı');setCv(d.text);setUpdatedCv('')}catch(err){alert(err.message||'CV yüklenemedi')}finally{setUploading(false);if(fileRef.current)fileRef.current.value=''}}
  function createCv(){const merged=mergeUnique(cv,linkedin);if(merged.length<40)return;setUpdatedCv(standardize(merged,standard))}
  async function findJobs(){if(cv.length<40)return;setJobsLoading(true);setJobsError('');setJobs([]);try{const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv,country})});const d=await r.json();if(!r.ok)throw new Error(d.error||'İlanlar alınamadı');setJobs(d.jobs||[]);setSources(d.sources||[]);setJobRole(d.role||'')}catch(e){setJobsError(e.message||'İlanlar alınamadı')}finally{setJobsLoading(false)}}
  function copyCv(){navigator.clipboard?.writeText(updatedCv)}
  return <main><nav className="nav wrap"><div className="brand"><span className="brandMark">J</span>JobFit</div><div className="topTabs"><button className={tab==='cv'?'active':''} onClick={()=>setTab('cv')}>CV Düzenle</button><button className={tab==='jobs'?'active':''} onClick={()=>setTab('jobs')}>İş Bul</button></div></nav>
  {tab==='cv'&&<><section className="hero wrap"><div className="eyebrow">JOBFIT CV STUDIO</div><h1>CV’ni bir kez yükle. <span>Doğru pazara göre yeniden oluştur.</span></h1><p>Mevcut CV ve LinkedIn bilgilerini karşılaştır, eksikleri gör ve Avrupa / İngiltere / ABD standardında yeni sürüm üret.</p></section><section className="wrap twoCol"><div className="panel"><div className="step">01</div><h2>Mevcut CV</h2><input ref={fileRef} className="fileInput" type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={handleFile}/><button className="uploadBox" onClick={()=>fileRef.current?.click()} disabled={uploading}><span className="uploadIcon">↑</span><strong>{uploading?'CV okunuyor…':fileName||'CV dosyası seç'}</strong><small>PDF · DOCX · TXT</small></button><textarea value={cv} onChange={e=>setCv(e.target.value)} placeholder="CV içeriği burada görünecek..." /></div><div className="panel"><div className="step">02</div><h2>LinkedIn profili</h2><label className="fieldLabel">LinkedIn URL</label><input className="textInput" value={linkedinUrl} onChange={e=>setLinkedinUrl(e.target.value)} placeholder="https://www.linkedin.com/in/..."/><p className="help">LinkedIn kişisel profil verisini tam olarak dışarı açmadığı için URL’yi kaydediyoruz; karşılaştırma için profilindeki About / Experience / Skills metnini buraya yapıştır.</p><textarea value={linkedin} onChange={e=>setLinkedin(e.target.value)} placeholder="LinkedIn About, Experience ve Skills içeriğini buraya yapıştır..." /></div></section><section className="wrap panel comparePanel"><div className="sectionHead"><div><div className="eyebrow">KARŞILAŞTIRMA</div><h2>CV ↔ LinkedIn</h2></div><span>{checks.filter(x=>x.cv&&x.linkedin).length}/10 ortak alan</span></div><div className="miniChecks">{checks.map(x=><div className="miniCheck" key={x.label}><strong>{x.label}</strong><span className={x.cv?'ok':'no'}>CV {x.cv?'✓':'–'}</span><span className={x.linkedin?'ok':'no'}>LinkedIn {x.linkedin?'✓':'–'}</span></div>)}</div></section><section className="wrap panel"><div className="sectionHead"><div><div className="eyebrow">HEDEF FORMAT</div><h2>CV standardını seç</h2></div></div><div className="standardGrid">{Object.entries(STANDARDS).map(([k,v])=><button key={k} className={`standardCard ${standard===k?'selected':''}`} onClick={()=>setStandard(k)}><strong>{v.label}</strong><small>{v.note}</small></button>)}</div><div className="actionRow"><button className="analyseBtn" disabled={cv.length<40} onClick={createCv}>CV’mi güncelle <span>→</span></button></div></section>{updatedCv&&<section className="wrap panel outputPanel"><div className="sectionHead"><div><div className="eyebrow">GÜNCELLENMİŞ CV</div><h2>{STANDARDS[standard].label} standardı taslak</h2></div><button className="ghost smallBtn" onClick={copyCv}>Kopyala</button></div><textarea value={updatedCv} onChange={e=>setUpdatedCv(e.target.value)} /></section>}</>}
  {tab==='jobs'&&<><section className="hero wrap"><div className="eyebrow">JOBFIT JOB DISCOVERY</div><h1>CV’ne göre iş bul. <span>Sadece ülkeyi seç.</span></h1><p>Rol ve yetkinlik filtresi CV’den otomatik çıkarılır. Kullanıcıdan yalnızca hedef ülke istenir.</p></section><section className="wrap panel jobFinder"><div className="step">01</div><h2>Hedef ülke</h2><select value={country} onChange={e=>setCountry(e.target.value)}>{COUNTRIES.map(c=><option key={c}>{c}</option>)}</select><div className="profileHint">{cv.length>40?'✓ CV profili hazır':'Önce CV Düzenle sekmesinden CV yükle'}</div><div className="actionRow"><button className="analyseBtn" disabled={cv.length<40||jobsLoading} onClick={findJobs}>{jobsLoading?'LinkedIn + Indeed + Kariyer taranıyor…':'CV’me uygun işleri bul'} <span>→</span></button></div></section>{jobRole&&<section className="wrap roleBar"><span>CV’den çıkarılan arama rolü</span><strong>{jobRole}</strong><b>{country}</b></section>}{jobsError&&<div className="wrap uploadError">{jobsError}</div>}{jobs.length>0&&<section className="wrap jobsGrid">{jobs.map((j,i)=><article className="jobCard" key={i}><div className="sourceBadge">{j.source}</div><h3>{j.title}</h3><p className="company">{j.company||'Şirket bilgisi yok'}</p><p className="location">{j.location||country}</p>{j.description&&<p className="desc">{j.description}</p>}{j.url&&<a href={j.url} target="_blank" rel="noreferrer">İlanı aç →</a>}</article>)}</section>}{sources.length>0&&<section className="wrap panel sourceFallback"><h3>Kaynak bağlantıları</h3><p>Bazı siteler ilan listesini otomatik okumaya kapatırsa doğrudan CV’ne göre hazırlanmış aramayı açabilirsin.</p><div className="sourceLinks">{sources.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer">{s.name} aramasını aç ↗</a>)}</div></section>}</>}
  <footer className="wrap">JobFit · CV Studio + Job Discovery</footer></main>}
