function cleanHtml(html=''){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function findJobs(value,out=[]){if(!value)return out;if(Array.isArray(value)){value.forEach(v=>findJobs(v,out));return out}if(typeof value!=='object')return out;const t=value['@type'];if(t==='JobPosting'||(Array.isArray(t)&&t.includes('JobPosting')))out.push(value);if(value['@graph'])findJobs(value['@graph'],out);Object.values(value).forEach(v=>{if(v&&typeof v==='object'&&v!==value['@graph'])findJobs(v,out)});return out}
function roleFromCv(cv=''){const t=cv.toLowerCase();if(t.includes('mechanical team lead'))return 'Mechanical Team Lead';if(t.includes('senior mechanical'))return 'Senior Mechanical Engineer';if(t.includes('piping')&&t.includes('hvac'))return 'Senior Mechanical Engineer';if(t.includes('piping'))return 'Piping Engineer';if(t.includes('hvac'))return 'HVAC Engineer';if(t.includes('software'))return 'Software Engineer';return 'Engineer'}
function mapJob(j,source){const loc=j.jobLocation?.address||j.jobLocation?.[0]?.address||{};const location=[loc.addressLocality,loc.addressRegion,loc.addressCountry].filter(Boolean).join(', ');return{title:cleanHtml(String(j.title||'')),company:cleanHtml(String(j.hiringOrganization?.name||'')),location,source,url:j.url||j.sameAs||'',description:cleanHtml(String(j.description||'')).slice(0,1600)}}
const STOP=new Set('the and for with from your our you are this that into will have has had job role team work working years year experience experienced required preferred looking company position based about who what where when how'.split(' '))
function terms(text=''){return [...new Set(text.toLowerCase().replace(/[^a-z0-9+#&.\-\s]/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)&&!/^\d+$/.test(x)))]}
function scoreJob(cv,job,role){const cvSet=new Set(terms(cv));const jobTerms=terms(`${job.title} ${job.description}`);let hit=0;for(const t of jobTerms)if(cvSet.has(t))hit++;const semantic=[['piping',['piping','pipe']],['hvac',['hvac','duct','ventilation']],['marine',['marine','ship','vessel','yacht','shipyard','naval']],['leadership',['lead','manager','coordination','subcontractor']],['design',['design','engineering','cadmatic','autocad','p&id']],['class',['solas','classification','dnv','lloyd','bv']]];let bonus=0;const c=cv.toLowerCase(),j=`${job.title} ${job.description}`.toLowerCase();for(const[,keys]of semantic){if(keys.some(k=>c.includes(k))&&keys.some(k=>j.includes(k)))bonus+=8}if(job.title.toLowerCase().includes(role.toLowerCase().split(' ')[0]))bonus+=8;const base=jobTerms.length?Math.min(50,Math.round(hit/jobTerms.length*100)):0;return Math.max(1,Math.min(99,base+bonus))}
async function fetchJobs(url,source){try{const r=await fetch(url,{cache:'no-store',redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; JobFit/1.0)','Accept-Language':'en-US,en;q=0.9,tr;q=0.8'},signal:AbortSignal.timeout(9000)});if(!r.ok)return[];const html=await r.text();const scripts=[...html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];const jobs=[];for(const m of scripts){try{findJobs(JSON.parse(m[1]),jobs)}catch{}}return jobs.slice(0,20).map(j=>mapJob(j,source)).filter(j=>j.title)}catch{return[]}}
export async function POST(request){try{const{cv,country='Netherlands'}=await request.json();if(!cv||cv.length<40)return Response.json({error:'Önce CV yükle.'},{status:400});const role=roleFromCv(cv);const q=encodeURIComponent(role);const loc=encodeURIComponent(country);const sources=[{name:'LinkedIn',url:`https://www.linkedin.com/jobs/search/?keywords=${q}&location=${loc}`},{name:'Indeed',url:`https://www.indeed.com/jobs?q=${q}&l=${loc}`},{name:'Kariyer.net',url:`https://www.kariyer.net/is-ilanlari?kw=${q}`}];const batches=await Promise.all(sources.map(s=>fetchJobs(s.url,s.name)));const seen=new Set();const jobs=batches.flat().filter(j=>{const k=(j.title+'|'+j.company+'|'+j.location).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).map(j=>({...j,fit:scoreJob(cv,j,role)})).sort((a,b)=>b.fit-a.fit).slice(0,10);return Response.json({role,country,jobs,sources:sources.map(s=>({name:s.name,url:s.url})),limited:jobs.length===0})}catch{return Response.json({error:'İlanlar alınamadı.'},{status:500})}}
